# Generated by Django 5.1.5 on 2026-09-20 19:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del sistema vendido.', max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('codigo', models.CharField(editable=False, help_text='Código de seguimiento que se entrega al cliente al comprar.', max_length=12, unique=True)),
                ('estado', models.CharField(choices=[('planificacion', 'En planificación'), ('diseno', 'En diseño'), ('desarrollo', 'En desarrollo'), ('revision', 'En revisión'), ('pruebas', 'En pruebas'), ('produccion', 'En producción'), ('entregado', 'Entregado'), ('pausado', 'Pausado')], default='planificacion', max_length=20)),
                ('avance', models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de avance 0-100 que actualiza el admin.')),
                ('email_cliente', models.EmailField(blank=True, default='', help_text='Correo del comprador al momento de la venta (respaldo).', max_length=254)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Usuario dueño del proyecto (se vincula con el código).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='ActualizacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True, default='')),
                ('avance', models.PositiveSmallIntegerField(blank=True, help_text='Si se indica, actualiza también el avance del proyecto.', null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizaciones_proyecto', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Actualización de proyecto',
                'verbose_name_plural': 'Actualizaciones de proyecto',
                'ordering': ['-creado'],
            },
        ),
    ]
